[tools]
python = "3.13"
uv = "latest"
node = "latest"
deno = "latest"
kubectl = "latest"
krew = "latest"
argo = "latest"
argocd = "latest"
argo-rollouts = "latest"
terraform = "latest"
awscli = "latest"
gcloud = "latest"
go = "1.24"
"npm:pnpm" = "latest"
"npm:@mermaid-js/mermaid-cli" = "latest"
rust = "1.91.1"
"cargo:silicon" = "0.5.1"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["terraform"]
